// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/debug.proto

package debug

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SpanType int32

const (
	SpanType_INBOUND  SpanType = 0
	SpanType_OUTBOUND SpanType = 1
)

var SpanType_name = map[int32]string{
	0: "INBOUND",
	1: "OUTBOUND",
}

var SpanType_value = map[string]int32{
	"INBOUND":  0,
	"OUTBOUND": 1,
}

func (x SpanType) String() string {
	return proto.EnumName(SpanType_name, int32(x))
}

func (SpanType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_466b588516b7ea56, []int{0}
}

type HealthRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthRequest) Reset()         { *m = HealthRequest{} }
func (m *HealthRequest) String() string { return proto.CompactTextString(m) }
func (*HealthRequest) ProtoMessage()    {}
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_466b588516b7ea56, []int{0}
}

func (m *HealthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthRequest.Unmarshal(m, b)
}
func (m *HealthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthRequest.Marshal(b, m, deterministic)
}
func (m *HealthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthRequest.Merge(m, src)
}
func (m *HealthRequest) XXX_Size() int {
	return xxx_messageInfo_HealthRequest.Size(m)
}
func (m *HealthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthRequest proto.InternalMessageInfo

type HealthResponse struct {
	// default: ok
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthResponse) Reset()         { *m = HealthResponse{} }
func (m *HealthResponse) String() string { return proto.CompactTextString(m) }
func (*HealthResponse) ProtoMessage()    {}
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_466b588516b7ea56, []int{1}
}

func (m *HealthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthResponse.Unmarshal(m, b)
}
func (m *HealthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthResponse.Marshal(b, m, deterministic)
}
func (m *HealthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthResponse.Merge(m, src)
}
func (m *HealthResponse) XXX_Size() int {
	return xxx_messageInfo_HealthResponse.Size(m)
}
func (m *HealthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthResponse proto.InternalMessageInfo

func (m *HealthResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type StatsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatsRequest) Reset()         { *m = StatsRequest{} }
func (m *StatsRequest) String() string { return proto.CompactTextString(m) }
func (*StatsRequest) ProtoMessage()    {}
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_466b588516b7ea56, []int{2}
}

func (m *StatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatsRequest.Unmarshal(m, b)
}
func (m *StatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatsRequest.Marshal(b, m, deterministic)
}
func (m *StatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatsRequest.Merge(m, src)
}
func (m *StatsRequest) XXX_Size() int {
	return xxx_messageInfo_StatsRequest.Size(m)
}
func (m *StatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatsRequest proto.InternalMessageInfo

type StatsResponse struct {
	// timestamp of recording
	Timestamp uint64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// unix timestamp
	Started uint64 `protobuf:"varint,2,opt,name=started,proto3" json:"started,omitempty"`
	// in seconds
	Uptime uint64 `protobuf:"varint,3,opt,name=uptime,proto3" json:"uptime,omitempty"`
	// in bytes
	Memory uint64 `protobuf:"varint,4,opt,name=memory,proto3" json:"memory,omitempty"`
	// num threads
	Threads uint64 `protobuf:"varint,5,opt,name=threads,proto3" json:"threads,omitempty"`
	// total gc in nanoseconds
	Gc uint64 `protobuf:"varint,6,opt,name=gc,proto3" json:"gc,omitempty"`
	// total number of requests
	Requests uint64 `protobuf:"varint,7,opt,name=requests,proto3" json:"requests,omitempty"`
	// total number of errors
	Errors               uint64   `protobuf:"varint,8,opt,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatsResponse) Reset()         { *m = StatsResponse{} }
func (m *StatsResponse) String() string { return proto.CompactTextString(m) }
func (*StatsResponse) ProtoMessage()    {}
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_466b588516b7ea56, []int{3}
}

func (m *StatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatsResponse.Unmarshal(m, b)
}
func (m *StatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatsResponse.Marshal(b, m, deterministic)
}
func (m *StatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatsResponse.Merge(m, src)
}
func (m *StatsResponse) XXX_Size() int {
	return xxx_messageInfo_StatsResponse.Size(m)
}
func (m *StatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatsResponse proto.InternalMessageInfo

func (m *StatsResponse) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *StatsResponse) GetStarted() uint64 {
	if m != nil {
		return m.Started
	}
	return 0
}

func (m *StatsResponse) GetUptime() uint64 {
	if m != nil {
		return m.Uptime
	}
	return 0
}

func (m *StatsResponse) GetMemory() uint64 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *StatsResponse) GetThreads() uint64 {
	if m != nil {
		return m.Threads
	}
	return 0
}

func (m *StatsResponse) GetGc() uint64 {
	if m != nil {
		return m.Gc
	}
	return 0
}

func (m *StatsResponse) GetRequests() uint64 {
	if m != nil {
		return m.Requests
	}
	return 0
}

func (m *StatsResponse) GetErrors() uint64 {
	if m != nil {
		return m.Errors
	}
	return 0
}

// LogRequest requests service logs
type LogRequest struct {
	// count of records to request
	Count int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	// relative time in seconds
	// before the current time
	// from which to show logs
	Since                int64    `protobuf:"varint,2,opt,name=since,proto3" json:"since,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogRequest) Reset()         { *m = LogRequest{} }
func (m *LogRequest) String() string { return proto.CompactTextString(m) }
func (*LogRequest) ProtoMessage()    {}
func (*LogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_466b588516b7ea56, []int{4}
}

func (m *LogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogRequest.Unmarshal(m, b)
}
func (m *LogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogRequest.Marshal(b, m, deterministic)
}
func (m *LogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogRequest.Merge(m, src)
}
func (m *LogRequest) XXX_Size() int {
	return xxx_messageInfo_LogRequest.Size(m)
}
func (m *LogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogRequest proto.InternalMessageInfo

func (m *LogRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *LogRequest) GetSince() int64 {
	if m != nil {
		return m.Since
	}
	return 0
}

// LogResponse returns a list of logs
type LogResponse struct {
	Records              []*Record `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LogResponse) Reset()         { *m = LogResponse{} }
func (m *LogResponse) String() string { return proto.CompactTextString(m) }
func (*LogResponse) ProtoMessage()    {}
func (*LogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_466b588516b7ea56, []int{5}
}

func (m *LogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogResponse.Unmarshal(m, b)
}
func (m *LogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogResponse.Marshal(b, m, deterministic)
}
func (m *LogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogResponse.Merge(m, src)
}
func (m *LogResponse) XXX_Size() int {
	return xxx_messageInfo_LogResponse.Size(m)
}
func (m *LogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogResponse proto.InternalMessageInfo

func (m *LogResponse) GetRecords() []*Record {
	if m != nil {
		return m.Records
	}
	return nil
}

// Record is service log record
type Record struct {
	// timestamp of log record
	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// record metadata
	Metadata map[string]string `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// message
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_466b588516b7ea56, []int{6}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Record) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Record) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type TraceRequest struct {
	// trace id to retrieve
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TraceRequest) Reset()         { *m = TraceRequest{} }
func (m *TraceRequest) String() string { return proto.CompactTextString(m) }
func (*TraceRequest) ProtoMessage()    {}
func (*TraceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_466b588516b7ea56, []int{7}
}

func (m *TraceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TraceRequest.Unmarshal(m, b)
}
func (m *TraceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TraceRequest.Marshal(b, m, deterministic)
}
func (m *TraceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TraceRequest.Merge(m, src)
}
func (m *TraceRequest) XXX_Size() int {
	return xxx_messageInfo_TraceRequest.Size(m)
}
func (m *TraceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TraceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TraceRequest proto.InternalMessageInfo

func (m *TraceRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type TraceResponse struct {
	Spans                []*Span  `protobuf:"bytes,1,rep,name=spans,proto3" json:"spans,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TraceResponse) Reset()         { *m = TraceResponse{} }
func (m *TraceResponse) String() string { return proto.CompactTextString(m) }
func (*TraceResponse) ProtoMessage()    {}
func (*TraceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_466b588516b7ea56, []int{8}
}

func (m *TraceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TraceResponse.Unmarshal(m, b)
}
func (m *TraceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TraceResponse.Marshal(b, m, deterministic)
}
func (m *TraceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TraceResponse.Merge(m, src)
}
func (m *TraceResponse) XXX_Size() int {
	return xxx_messageInfo_TraceResponse.Size(m)
}
func (m *TraceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TraceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TraceResponse proto.InternalMessageInfo

func (m *TraceResponse) GetSpans() []*Span {
	if m != nil {
		return m.Spans
	}
	return nil
}

type Span struct {
	// the trace id
	Trace string `protobuf:"bytes,1,opt,name=trace,proto3" json:"trace,omitempty"`
	// id of the span
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// parent span
	Parent string `protobuf:"bytes,3,opt,name=parent,proto3" json:"parent,omitempty"`
	// name of the resource
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// time of start in nanoseconds
	Started uint64 `protobuf:"varint,5,opt,name=started,proto3" json:"started,omitempty"`
	// duration of the execution in nanoseconds
	Duration uint64 `protobuf:"varint,6,opt,name=duration,proto3" json:"duration,omitempty"`
	// associated metadata
	Metadata             map[string]string `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Type                 SpanType          `protobuf:"varint,8,opt,name=type,proto3,enum=SpanType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Span) Reset()         { *m = Span{} }
func (m *Span) String() string { return proto.CompactTextString(m) }
func (*Span) ProtoMessage()    {}
func (*Span) Descriptor() ([]byte, []int) {
	return fileDescriptor_466b588516b7ea56, []int{9}
}

func (m *Span) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Span.Unmarshal(m, b)
}
func (m *Span) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Span.Marshal(b, m, deterministic)
}
func (m *Span) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Span.Merge(m, src)
}
func (m *Span) XXX_Size() int {
	return xxx_messageInfo_Span.Size(m)
}
func (m *Span) XXX_DiscardUnknown() {
	xxx_messageInfo_Span.DiscardUnknown(m)
}

var xxx_messageInfo_Span proto.InternalMessageInfo

func (m *Span) GetTrace() string {
	if m != nil {
		return m.Trace
	}
	return ""
}

func (m *Span) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Span) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *Span) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Span) GetStarted() uint64 {
	if m != nil {
		return m.Started
	}
	return 0
}

func (m *Span) GetDuration() uint64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Span) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *Span) GetType() SpanType {
	if m != nil {
		return m.Type
	}
	return SpanType_INBOUND
}

func init() {
	proto.RegisterEnum("SpanType", SpanType_name, SpanType_value)
	proto.RegisterType((*HealthRequest)(nil), "HealthRequest")
	proto.RegisterType((*HealthResponse)(nil), "HealthResponse")
	proto.RegisterType((*StatsRequest)(nil), "StatsRequest")
	proto.RegisterType((*StatsResponse)(nil), "StatsResponse")
	proto.RegisterType((*LogRequest)(nil), "LogRequest")
	proto.RegisterType((*LogResponse)(nil), "LogResponse")
	proto.RegisterType((*Record)(nil), "Record")
	proto.RegisterMapType((map[string]string)(nil), "Record.MetadataEntry")
	proto.RegisterType((*TraceRequest)(nil), "TraceRequest")
	proto.RegisterType((*TraceResponse)(nil), "TraceResponse")
	proto.RegisterType((*Span)(nil), "Span")
	proto.RegisterMapType((map[string]string)(nil), "Span.MetadataEntry")
}

func init() {
	proto.RegisterFile("proto/debug.proto", fileDescriptor_466b588516b7ea56)
}

var fileDescriptor_466b588516b7ea56 = []byte{
	// 647 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0xfd, 0x6c, 0xc7, 0x71, 0x7c, 0x93, 0xb8, 0xed, 0x7c, 0x3f, 0xb2, 0xfc, 0x15, 0x04, 0x23,
	0x21, 0x55, 0x15, 0xb2, 0x69, 0xd9, 0x94, 0x22, 0x36, 0xa8, 0x48, 0x20, 0x95, 0x56, 0x9a, 0xb6,
	0x0f, 0x30, 0x8d, 0x47, 0x6e, 0x44, 0xec, 0x31, 0x33, 0x63, 0xa4, 0x6c, 0x79, 0x05, 0x96, 0xbc,
	0x04, 0xef, 0x82, 0x78, 0x03, 0xf6, 0xbc, 0x02, 0x9a, 0x1f, 0xb7, 0x8e, 0x10, 0x2b, 0x76, 0x73,
	0xce, 0x9d, 0x73, 0x33, 0xf7, 0xf8, 0xe4, 0xc2, 0x4e, 0x2b, 0xb8, 0xe2, 0x45, 0xc9, 0xae, 0xbb,
	0x2a, 0x37, 0xe7, 0x6c, 0xb7, 0xe2, 0xbc, 0x5a, 0xb1, 0x82, 0xb6, 0xcb, 0x82, 0x36, 0x0d, 0x57,
	0x54, 0x2d, 0x79, 0x23, 0x6d, 0x15, 0x6f, 0xc1, 0xfc, 0x35, 0xa3, 0x2b, 0x75, 0x43, 0xd8, 0xfb,
	0x8e, 0x49, 0x85, 0xf7, 0x20, 0xe9, 0x09, 0xd9, 0xf2, 0x46, 0x32, 0xf4, 0x1f, 0x8c, 0xa5, 0xa2,
	0xaa, 0x93, 0xa9, 0xf7, 0xc0, 0xdb, 0x8b, 0x89, 0x43, 0x38, 0x81, 0xd9, 0x85, 0xa2, 0x4a, 0xf6,
	0xca, 0x6f, 0x1e, 0xcc, 0x1d, 0xe1, 0x94, 0xbb, 0x10, 0xab, 0x65, 0xcd, 0xa4, 0xa2, 0x75, 0x6b,
	0xc4, 0x23, 0x72, 0x47, 0xa0, 0x14, 0x22, 0xa9, 0xa8, 0x50, 0xac, 0x4c, 0x7d, 0x53, 0xeb, 0xa1,
	0xfe, 0xc5, 0xae, 0xd5, 0x17, 0xd3, 0xc0, 0x14, 0x1c, 0xd2, 0x7c, 0xcd, 0x6a, 0x2e, 0xd6, 0xe9,
	0xc8, 0xf2, 0x16, 0xe9, 0x4e, 0xea, 0x46, 0x30, 0x5a, 0xca, 0x34, 0xb4, 0x9d, 0x1c, 0x44, 0x09,
	0xf8, 0xd5, 0x22, 0x1d, 0x1b, 0xd2, 0xaf, 0x16, 0x28, 0x83, 0x89, 0xb0, 0xcf, 0x95, 0x69, 0x64,
	0xd8, 0x5b, 0xac, 0xbb, 0x33, 0x21, 0xb8, 0x90, 0xe9, 0xc4, 0x76, 0xb7, 0x08, 0x1f, 0x01, 0x9c,
	0xf2, 0xca, 0x4d, 0x89, 0xfe, 0x81, 0x70, 0xc1, 0xbb, 0x46, 0x99, 0x79, 0x02, 0x62, 0x81, 0x66,
	0xe5, 0xb2, 0x59, 0x30, 0x33, 0x49, 0x40, 0x2c, 0xc0, 0x4f, 0x60, 0x6a, 0x94, 0xce, 0x8e, 0x87,
	0x10, 0x09, 0xb6, 0xe0, 0xa2, 0xd4, 0x4e, 0x06, 0x7b, 0xd3, 0xc3, 0x28, 0x27, 0x06, 0x93, 0x9e,
	0xc7, 0x5f, 0x3c, 0x18, 0x5b, 0xee, 0x57, 0xf3, 0x82, 0xa1, 0x79, 0x07, 0x30, 0xa9, 0x99, 0xa2,
	0x25, 0x55, 0x34, 0xf5, 0x4d, 0xb3, 0x7f, 0x5d, 0xb3, 0xfc, 0xad, 0xe3, 0x5f, 0x35, 0x4a, 0xac,
	0xc9, 0xed, 0x35, 0xed, 0x52, 0xcd, 0xa4, 0xa4, 0x95, 0xb5, 0x35, 0x26, 0x3d, 0xcc, 0x9e, 0xc3,
	0x7c, 0x43, 0x84, 0xb6, 0x21, 0x78, 0xc7, 0xd6, 0xee, 0x7b, 0xeb, 0xa3, 0x1e, 0xf0, 0x03, 0x5d,
	0x75, 0x76, 0xc0, 0x98, 0x58, 0x70, 0xec, 0x1f, 0x79, 0xf8, 0x3e, 0xcc, 0x2e, 0x05, 0x5d, 0xb0,
	0xde, 0xa0, 0x04, 0xfc, 0x65, 0xe9, 0xa4, 0xfe, 0xb2, 0xc4, 0x8f, 0x61, 0xee, 0xea, 0xce, 0x86,
	0xff, 0x21, 0x94, 0x2d, 0x6d, 0x7a, 0x13, 0xc2, 0xfc, 0xa2, 0xa5, 0x0d, 0xb1, 0x1c, 0xfe, 0xec,
	0xc3, 0x48, 0x63, 0xfd, 0x83, 0x4a, 0xcb, 0x5c, 0x27, 0x0b, 0x5c, 0x73, 0xbf, 0x6f, 0xae, 0xbf,
	0x59, 0x4b, 0x05, 0x6b, 0x94, 0x1b, 0xc9, 0x21, 0x84, 0x60, 0xd4, 0xd0, 0x9a, 0x99, 0x9c, 0xc4,
	0xc4, 0x9c, 0x87, 0x79, 0x0b, 0x37, 0xf3, 0x96, 0xc1, 0xa4, 0xec, 0x84, 0xf9, 0x5f, 0xb8, 0xac,
	0xdc, 0x62, 0x54, 0x0c, 0x8c, 0x8e, 0xcc, 0x83, 0xff, 0x36, 0x0f, 0xfe, 0xad, 0xcd, 0xf7, 0x60,
	0xa4, 0xd6, 0x2d, 0x33, 0x21, 0x4a, 0x0e, 0x63, 0x73, 0xf9, 0x72, 0xdd, 0x32, 0x62, 0xe8, 0x3f,
	0xf2, 0x7a, 0xff, 0x11, 0x4c, 0xfa, 0x76, 0x68, 0x0a, 0xd1, 0x9b, 0xb3, 0x97, 0xe7, 0x57, 0x67,
	0x27, 0xdb, 0x7f, 0xa1, 0x19, 0x4c, 0xce, 0xaf, 0x2e, 0x2d, 0xf2, 0x0e, 0x7f, 0x78, 0x10, 0x9e,
	0xe8, 0x15, 0x80, 0x0e, 0x20, 0x38, 0xe5, 0x15, 0x9a, 0xe6, 0x77, 0x09, 0xce, 0x66, 0xf9, 0x20,
	0x94, 0x78, 0xeb, 0xe3, 0xd7, 0xef, 0x9f, 0xfc, 0x18, 0x8f, 0x8a, 0x15, 0xaf, 0x8e, 0xbd, 0x7d,
	0xf4, 0x02, 0xc6, 0x76, 0x01, 0xa0, 0x24, 0xdf, 0x58, 0x0d, 0xd9, 0x56, 0xbe, 0xb9, 0x19, 0x30,
	0x32, 0xda, 0x19, 0x8e, 0x8a, 0x1b, 0x53, 0xd0, 0xf2, 0x67, 0x10, 0x9a, 0x25, 0x80, 0xe6, 0xf9,
	0x70, 0x3b, 0x64, 0x49, 0xbe, 0xb1, 0x1b, 0xf0, 0x8e, 0xd1, 0x4e, 0xf1, 0xb8, 0xd0, 0xeb, 0x44,
	0x3a, 0xa9, 0x49, 0x0a, 0x9a, 0xe7, 0xc3, 0x44, 0x65, 0x49, 0xbe, 0x11, 0xa0, 0x81, 0xd4, 0x84,
	0xe2, 0xd8, 0xdb, 0xbf, 0x1e, 0x9b, 0x6d, 0xf6, 0xf4, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0a,
	0x40, 0x85, 0x9b, 0x00, 0x05, 0x00, 0x00,
}
